version: 2.1

jobs:
  backend_build:
    working_directory: ~/backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd backend && npm install
      - run:
          name: Lint and test
          command: cd backend && npm run lint

  frontend_build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd frontend && npm install
      - run:
          name: Lint project & run test
          command: cd frontend && npm run lint
      - run:
          name: frontend_build
          command: cd frontend && npm run build
workflows:
  version: 2

  my_workflow:
    jobs:
      - backend_build
      - frontend_build:
          requires:
            - backend_build
