version: 2.1

jobs:
  build:
    working_directory: ~/backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
  build2:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install

workflows:
  version: 2

  my_workflow:
    jobs:
      - build
      - build2:
          requires:
            - build
