version: 2.1

jobs:
  build:
    working_directory: ~/backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: docker backend
          command: docker-compose up
  build2:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: docker frontend
          command: docker-compose up

workflows:
  version: 2.1

  my_workflow:
    jobs:
      - build
      - build2:
          requires:
            - build
